-- Kitscore database schema baseline -- snapshot as of 2026-07-15
--
-- Generated by querying pg_proc / pg_trigger / pg_policy directly against
-- the live Supabase project (tpcriphrfrrgywycviqv). This is a REFERENCE
-- SNAPSHOT documenting what exists, not a migration meant to be replayed.
-- Supersedes schema-baseline-2026-07-04.sql, which had drifted ~11 days
-- behind live (missing, among other things, creator_collaborations,
-- creator_press_mentions, available_for/causes/theme on creators, and
-- view_count on platform_connections). See README.md in this folder for
-- why this file exists and the practice going forward.

-- =============================================================
-- FUNCTIONS
-- =============================================================

CREATE OR REPLACE FUNCTION public.check_evaluation_completeness()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  completeness NUMERIC;
BEGIN
  completeness := creator_score_completeness(NEW.creator_id);
  IF completeness < 50 THEN
    RAISE EXCEPTION
      'Creator score is only % complete. At least 50%% of score components must be filled before an evaluation can be unlocked.',
      completeness;
  END IF;
  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.compute_creator_reliability(p_creator_id uuid)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_total_campaigns integer;
  v_verified_campaigns integer;
  v_completion_rate numeric;
  v_has_sponsor_rating boolean;
  v_avg_sponsor_rating numeric;
  v_has_endorsement boolean;
  v_avg_endorsement numeric;
  v_total_sponsors integer;
  v_repeat_sponsors integer;
  v_repeat_rate numeric;
  v_has_would_hire boolean;
  v_would_hire_count integer;
  v_would_hire_yes integer;
  v_would_hire_pct numeric;
  v_weight_used numeric := 0;
  v_score_sum numeric := 0;
  v_reliability numeric;
begin
  select count(*), count(*) filter (where creator_confirmed = true and sponsor_confirmed = true)
  into v_total_campaigns, v_verified_campaigns
  from campaigns where creator_id = p_creator_id;

  if v_total_campaigns = 0 then
    update creators set
      reliability_score = 0, repeat_sponsor_rate = 0, would_hire_again_pct = 0, updated_at = now()
    where id = p_creator_id;
    return 0;
  end if;

  v_completion_rate := (v_verified_campaigns::numeric / v_total_campaigns) * 100;

  select avg(sponsor_rating) * 20, count(*) > 0
  into v_avg_sponsor_rating, v_has_sponsor_rating
  from campaigns where creator_id = p_creator_id and sponsor_rating is not null;
  v_avg_sponsor_rating := coalesce(v_avg_sponsor_rating, 0);

  select avg((coalesce(communication_rating,0) + coalesce(professionalism_rating,0) + coalesce(deliverable_quality_rating,0)) / 3.0) * 20
  into v_avg_endorsement
  from campaigns where creator_id = p_creator_id and endorsement_submitted_at is not null;
  v_has_endorsement := v_avg_endorsement is not null;
  v_avg_endorsement := coalesce(v_avg_endorsement, 0);

  select count(distinct sponsor_id)
  into v_total_sponsors
  from campaigns where creator_id = p_creator_id and creator_confirmed = true and sponsor_confirmed = true;

  select count(*) into v_repeat_sponsors from (
    select sponsor_id from campaigns
    where creator_id = p_creator_id and creator_confirmed = true and sponsor_confirmed = true
    group by sponsor_id having count(*) > 1
  ) sub;

  v_repeat_rate := case when v_total_sponsors > 0 then (v_repeat_sponsors::numeric / v_total_sponsors) * 100 else 0 end;

  select count(*) filter (where would_hire_again is not null),
         count(*) filter (where would_hire_again = true)
  into v_would_hire_count, v_would_hire_yes
  from campaigns where creator_id = p_creator_id;

  v_has_would_hire := v_would_hire_count > 0;
  v_would_hire_pct := case when v_would_hire_count > 0 then (v_would_hire_yes::numeric / v_would_hire_count) * 100 else 0 end;

  v_score_sum := v_completion_rate * 30;
  v_weight_used := 30;

  if v_has_sponsor_rating then
    v_score_sum := v_score_sum + v_avg_sponsor_rating * 25;
    v_weight_used := v_weight_used + 25;
  end if;

  if v_has_endorsement then
    v_score_sum := v_score_sum + v_avg_endorsement * 20;
    v_weight_used := v_weight_used + 20;
  end if;

  if v_total_sponsors > 0 then
    v_score_sum := v_score_sum + v_repeat_rate * 15;
    v_weight_used := v_weight_used + 15;
  end if;

  if v_has_would_hire then
    v_score_sum := v_score_sum + v_would_hire_pct * 10;
    v_weight_used := v_weight_used + 10;
  end if;

  v_reliability := round(v_score_sum / v_weight_used);

  update creators set
    reliability_score = v_reliability,
    repeat_sponsor_rate = round(v_repeat_rate),
    would_hire_again_pct = round(v_would_hire_pct),
    updated_at = now()
  where id = p_creator_id;

  return v_reliability;
end;
$function$


CREATE OR REPLACE FUNCTION public.creator_score_completeness(p_creator_id uuid)
 RETURNS numeric
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT CASE
    WHEN COUNT(*) = 0 THEN 0
    ELSE ROUND(
      COUNT(*) FILTER (WHERE value IS NOT NULL AND value > 0)::NUMERIC
      / COUNT(*)::NUMERIC * 100, 1
    )
  END
  FROM score_components
  WHERE creator_id = p_creator_id;
$function$


CREATE OR REPLACE FUNCTION public.find_sponsor_by_profile_or_stripe(p_stripe_customer_id text, p_profile_id uuid DEFAULT NULL::uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id UUID;
BEGIN
  SELECT id INTO v_id FROM sponsors WHERE stripe_customer_id = p_stripe_customer_id LIMIT 1;
  IF v_id IS NOT NULL THEN RETURN v_id; END IF;
  IF p_profile_id IS NOT NULL THEN
    SELECT id INTO v_id FROM sponsors WHERE id = p_profile_id LIMIT 1;
  END IF;
  RETURN v_id;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_admin_apply_brand_safety_scan(p_scan_id uuid, p_decision text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_scan record;
  v_gambling_flagged boolean;
  v_adult_flagged boolean;
  v_other_flagged boolean;
  v_self_gambling numeric;
  v_self_adult numeric;
  v_self_family numeric;
  v_self_other_total numeric;
  v_effective_gambling numeric;
  v_effective_adult numeric;
  v_effective_family numeric;
  v_total numeric;
begin
  if not fn_is_admin() then
    raise exception 'ADMIN_ONLY: only admins can review brand safety scans';
  end if;

  if p_decision not in ('approved', 'rejected') then
    raise exception 'INVALID_DECISION: must be approved or rejected';
  end if;

  select * into v_scan from brand_safety_scans where id = p_scan_id and status = 'pending_review';
  if v_scan is null then
    raise exception 'NOT_FOUND: no pending scan with that id';
  end if;

  if p_decision = 'rejected' then
    update brand_safety_scans set status = 'rejected', reviewed_at = now() where id = p_scan_id;
    return;
  end if;

  v_gambling_flagged := 'gambling' = ANY(v_scan.categories);
  v_adult_flagged := 'adult_content' = ANY(v_scan.categories);
  v_other_flagged := EXISTS (
    SELECT 1 FROM unnest(v_scan.categories) c WHERE c NOT IN ('gambling', 'adult_content')
  );

  SELECT coalesce(sum(p.penalty) FILTER (WHERE a.question_key = 'gambling'), 0),
         coalesce(sum(p.penalty) FILTER (WHERE a.question_key = 'adult'), 0),
         coalesce(sum(p.penalty) FILTER (WHERE a.question_key = 'family_safe'), 0),
         coalesce(sum(p.penalty) FILTER (WHERE a.question_key NOT IN ('gambling', 'adult', 'family_safe')), 0)
    INTO v_self_gambling, v_self_adult, v_self_family, v_self_other_total
    FROM brand_safety_answers a
    JOIN brand_safety_penalties p ON p.question_key = a.question_key AND p.answer = a.answer
    WHERE a.creator_id = v_scan.creator_id;

  v_effective_gambling := CASE WHEN v_gambling_flagged THEN LEAST(coalesce(v_self_gambling,0), -25) ELSE coalesce(v_self_gambling,0) END;
  v_effective_adult := CASE WHEN v_adult_flagged THEN LEAST(coalesce(v_self_adult,0), -30) ELSE coalesce(v_self_adult,0) END;
  v_effective_family := CASE WHEN v_other_flagged THEN LEAST(coalesce(v_self_family,0), -20) ELSE coalesce(v_self_family,0) END;

  v_total := greatest(100 + v_effective_gambling + v_effective_adult + v_effective_family + coalesce(v_self_other_total,0), 0);

  INSERT INTO score_components (creator_id, component_key, label, weight, value, status)
  VALUES (v_scan.creator_id, 'brand_safety', 'Brand safety', 0.20, v_total, 'scan_reviewed')
  ON CONFLICT (creator_id, component_key)
  DO UPDATE SET value = excluded.value, status = 'scan_reviewed', updated_at = now();

  UPDATE brand_safety_scans SET status = 'approved', reviewed_at = now() WHERE id = p_scan_id;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_admin_flag_creator(p_profile_id uuid, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  v_admin_id uuid;
begin
  if not fn_is_admin() then
    raise exception 'Admin only';
  end if;
  select id into v_admin_id from profiles where auth_user_id = auth.uid();
  insert into admin_flags (creator_profile_id, flagged_by, reason)
  values (p_profile_id, v_admin_id, p_reason);
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_admin_list_creator_directory()
 RETURNS TABLE(profile_id uuid, display_name text, email text, created_at timestamp with time zone, plan text, trust_score numeric, badge_tier text, founding_cohort boolean, is_flagged boolean)
 LANGUAGE plpgsql
AS $function$
begin
  if not fn_is_admin() then
    raise exception 'Admin only';
  end if;
  return query
    select
      p.id,
      p.display_name,
      p.email,
      p.created_at,
      c.plan::text,
      c.trust_score,
      c.badge_tier::text,
      c.founding_cohort,
      exists(select 1 from admin_flags af where af.creator_profile_id = p.id and af.resolved = false)
    from profiles p
    join creators c on c.id = p.id
    where p.role = 'creator'
    order by p.created_at desc;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_admin_list_profiles()
 RETURNS SETOF profiles
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not fn_is_admin() then
    raise exception 'Admin only';
  end if;
  return query select * from profiles order by created_at desc;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_campaign_mutual_confirm()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if new.creator_confirmed and new.sponsor_confirmed and old.status != 'verified' then
    new.status := 'verified';
    new.verified_at := now();
  end if;
  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_capture_trust_score_at_approval()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.approval_status = 'approved' AND (OLD.approval_status IS DISTINCT FROM 'approved') THEN
    SELECT trust_score INTO NEW.trust_score_at_approval FROM creators WHERE id = NEW.creator_id;
  END IF;
  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_capture_trust_score_history()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.trust_score IS DISTINCT FROM OLD.trust_score
     OR NEW.confidence IS DISTINCT FROM OLD.confidence THEN
    INSERT INTO trust_score_history (creator_id, trust_score, confidence, recorded_at)
    VALUES (NEW.id, NEW.trust_score, NEW.confidence, now());
  END IF;
  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_claim_free_eval_unlock(p_sponsor_id uuid)
 RETURNS TABLE(claimed boolean, new_used integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_new_used integer;
BEGIN
  UPDATE sponsors
  SET evals_used_this_period = evals_used_this_period + 1
  WHERE id = p_sponsor_id
    AND plan = 'starter'
    AND evals_used_this_period < 25
  RETURNING evals_used_this_period INTO v_new_used;

  IF v_new_used IS NOT NULL THEN
    RETURN QUERY SELECT true, v_new_used;
  ELSE
    RETURN QUERY SELECT false, NULL::integer;
  END IF;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_confidence_on_evidence_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM fn_recalc_creator_confidence(COALESCE(NEW.creator_id, OLD.creator_id));
  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_confidence_on_platform_connection_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM fn_recalc_creator_confidence(COALESCE(NEW.creator_id, OLD.creator_id));
  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_confirm_campaign_invite(p_token text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_invite record;
  v_sponsor_profile record;
  v_auth_email text;
  v_campaign_id uuid;
BEGIN
  SELECT * INTO v_invite FROM campaign_confirmation_invites WHERE token = p_token;
  IF v_invite IS NULL THEN
    RAISE EXCEPTION 'Invite not found';
  END IF;

  IF v_invite.status = 'confirmed' THEN
    RETURN v_invite.campaign_id;
  END IF;

  IF v_invite.expires_at < now() THEN
    UPDATE campaign_confirmation_invites SET status = 'expired' WHERE id = v_invite.id;
    RAISE EXCEPTION 'This invite has expired';
  END IF;

  SELECT p.* INTO v_sponsor_profile
  FROM profiles p
  WHERE p.auth_user_id = auth.uid() AND p.role = 'sponsor';

  IF v_sponsor_profile IS NULL THEN
    RAISE EXCEPTION 'Not authenticated as a sponsor';
  END IF;

  v_auth_email := auth.jwt() ->> 'email';

  IF v_auth_email IS NULL OR lower(v_auth_email) IS DISTINCT FROM lower(v_invite.sponsor_email) THEN
    RAISE EXCEPTION 'This invite was sent to a different email address';
  END IF;

  INSERT INTO campaigns (creator_id, sponsor_id, name, creator_confirmed, sponsor_confirmed, status, budget_range, objective, verified_at)
  VALUES (
    v_invite.creator_id,
    v_sponsor_profile.id,
    COALESCE(v_invite.description, 'Confirmed campaign'),
    true, true, 'verified',
    v_invite.budget_range,
    v_invite.description,
    now()
  )
  RETURNING id INTO v_campaign_id;

  UPDATE campaign_confirmation_invites
  SET status = 'confirmed', confirmed_at = now(), campaign_id = v_campaign_id
  WHERE id = v_invite.id;

  RETURN v_campaign_id;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_creator_platform_summary(p_creator_id uuid)
 RETURNS TABLE(platform text, platform_handle text, verification_method text, follower_count bigint, video_count bigint, view_count bigint, last_synced_at timestamp with time zone, connected_at timestamp with time zone)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT platform, platform_handle, verification_method,
         follower_count, video_count, view_count,
         last_synced_at, connected_at
  FROM public.platform_connections
  WHERE creator_id = p_creator_id;
$function$


CREATE OR REPLACE FUNCTION public.fn_current_profile_id()
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select id from profiles where auth_user_id = auth.uid();
$function$


CREATE OR REPLACE FUNCTION public.fn_current_role()
 RETURNS user_role
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select role from profiles where auth_user_id = auth.uid();
$function$


CREATE OR REPLACE FUNCTION public.fn_enforce_platform_cap()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_is_unlimited boolean;
  v_new_platform text;
  v_existing_platforms text[];
BEGIN
  SELECT (plan = 'pro' OR founding_cohort) INTO v_is_unlimited
  FROM creators WHERE id = NEW.creator_id;

  IF v_is_unlimited THEN
    RETURN NEW;
  END IF;

  v_new_platform := lower(NEW.platform);
  IF v_new_platform IS NULL OR v_new_platform = '' THEN
    RETURN NEW;
  END IF;

  SELECT array_agg(DISTINCT lower(platform)) INTO v_existing_platforms
  FROM platform_connections
  WHERE creator_id = NEW.creator_id AND verification_method = 'oauth';

  IF v_existing_platforms IS NOT NULL
     AND array_length(v_existing_platforms, 1) >= 1
     AND NOT (v_new_platform = ANY(v_existing_platforms)) THEN
    RAISE EXCEPTION 'PLATFORM_CAP: Free plan is limited to one OAuth-verified platform. Upgrade to Pro for unlimited platforms.';
  END IF;

  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_enforce_team_cap()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF fn_owned_team_count(NEW.owner_id) >= 3 THEN
    RAISE EXCEPTION 'You can own a maximum of 3 active teams. Archive one before creating another.';
  END IF;
  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_enforce_watchlist_limit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  sponsor_plan plan_tier;
  current_count int;
  max_allowed int;
begin
  select plan into sponsor_plan from sponsors where id = new.sponsor_id;
  max_allowed := case when sponsor_plan = 'free' then 3 else null end;

  if max_allowed is not null then
    select count(*) into current_count from watchlists where sponsor_id = new.sponsor_id;
    if current_count >= max_allowed then
      raise exception 'Free plan is limited to % saved creators. Upgrade to save more.', max_allowed;
    end if;
  end if;

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_flag_failed_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_req record;
begin
  select * into v_req from public.notification_requests where net_request_id = new.id;
  if v_req.net_request_id is null then
    return new;
  end if;

  if new.timed_out is true or new.status_code is null or new.status_code < 200 or new.status_code >= 300 then
    insert into public.notification_failures (kind, recipient_email, error, attempts, created_at, last_attempted_at)
    values (
      v_req.kind,
      v_req.recipient_email,
      coalesce(new.error_msg, 'HTTP ' || coalesce(new.status_code::text, 'no response')) || (case when new.timed_out then ' (timed out)' else '' end),
      1, now(), now()
    );
  end if;

  delete from public.notification_requests where net_request_id = new.id;
  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_generate_creator_slug()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_display_name text;
  v_base text;
  v_slug text;
BEGIN
  IF new.slug IS NOT NULL THEN
    RETURN new;
  END IF;

  SELECT display_name INTO v_display_name FROM profiles WHERE id = new.id;
  v_base := lower(regexp_replace(coalesce(v_display_name, 'creator'), '[^a-zA-Z0-9]+', '-', 'g'));
  v_base := trim(both '-' from v_base);
  IF v_base = '' THEN v_base := 'creator'; END IF;

  v_slug := v_base || '-' || substr(encode(gen_random_bytes(3), 'hex'), 1, 5);
  WHILE EXISTS(SELECT 1 FROM creators WHERE slug = v_slug) LOOP
    v_slug := v_base || '-' || substr(encode(gen_random_bytes(3), 'hex'), 1, 5);
  END LOOP;

  new.slug := v_slug;
  RETURN new;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_get_evekit_profile(p_slug text)
 RETURNS TABLE(display_name text, niche text, location text, bio text, business_email text, avatar_url text, gallery_images jsonb, available_for text[], causes text[], theme text, trust_score numeric, confidence numeric, badge_tier text, founding_cohort boolean, reliability_score numeric, verified_campaign_count bigint, profile_views integer, audience_countries jsonb, audience_genders jsonb, audience_ages jsonb, platforms jsonb, campaigns jsonb, collaborations jsonb, press_mentions jsonb)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    p.display_name, c.niche, c.location, c.bio, c.business_email,
    c.avatar_url, c.gallery_images, c.available_for, c.causes, c.theme,
    c.trust_score, c.confidence::numeric, c.badge_tier, c.founding_cohort,
    c.reliability_score,
    (SELECT count(*) FROM campaigns cam WHERE cam.creator_id = c.id AND cam.creator_confirmed AND cam.sponsor_confirmed),
    c.profile_views,
    COALESCE(
      (SELECT jsonb_agg(jsonb_build_object('label', ad.label, 'pct', ad.pct) ORDER BY ad.pct DESC)
       FROM audience_demographics ad WHERE ad.creator_id = c.id AND ad.dimension = 'country'),
      '[]'::jsonb
    ),
    COALESCE(
      (SELECT jsonb_agg(jsonb_build_object('label', ad.label, 'pct', ad.pct) ORDER BY ad.pct DESC)
       FROM audience_demographics ad WHERE ad.creator_id = c.id AND ad.dimension = 'gender'),
      '[]'::jsonb
    ),
    COALESCE(
      (SELECT jsonb_agg(jsonb_build_object('label', ad.label, 'pct', ad.pct) ORDER BY ad.pct DESC)
       FROM audience_demographics ad WHERE ad.creator_id = c.id AND ad.dimension = 'age'),
      '[]'::jsonb
    ),
    COALESCE(
      (SELECT jsonb_agg(jsonb_build_object(
         'platform', pc.platform, 'platform_handle', pc.platform_handle,
         'follower_count', pc.follower_count, 'video_count', pc.video_count,
         'view_count', pc.view_count, 'verification_method', pc.verification_method
       ) ORDER BY pc.follower_count DESC NULLS LAST)
       FROM platform_connections pc WHERE pc.creator_id = c.id AND pc.follower_count IS NOT NULL),
      '[]'::jsonb
    ),
    COALESCE(
      (SELECT jsonb_agg(jsonb_build_object(
         'name', cam.name, 'objective', cam.objective, 'completed_at', cam.completed_at
       ) ORDER BY cam.created_at DESC)
       FROM (
         SELECT * FROM campaigns cam2
         WHERE cam2.creator_id = c.id AND cam2.creator_confirmed AND cam2.sponsor_confirmed
         ORDER BY cam2.created_at DESC
         LIMIT 6
       ) cam),
      '[]'::jsonb
    ),
    COALESCE(
      (SELECT jsonb_agg(jsonb_build_object(
         'brand_name', cc.brand_name, 'logo_url', cc.logo_url, 'link', cc.link
       ) ORDER BY cc.display_order, cc.created_at)
       FROM creator_collaborations cc WHERE cc.creator_id = c.id),
      '[]'::jsonb
    ),
    COALESCE(
      (SELECT jsonb_agg(jsonb_build_object(
         'id', cpm.id, 'title', cpm.title, 'outlet_name', cpm.outlet_name,
         'url', cpm.url, 'mention_date', cpm.mention_date
       ) ORDER BY cpm.display_order, cpm.created_at)
       FROM creator_press_mentions cpm WHERE cpm.creator_id = c.id),
      '[]'::jsonb
    )
  FROM creators c
  JOIN profiles p ON p.id = c.id
  WHERE c.slug = p_slug AND c.is_test = false;
$function$


CREATE OR REPLACE FUNCTION public.fn_get_my_business_email()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select business_email from creators where id = fn_current_profile_id();
$function$


CREATE OR REPLACE FUNCTION public.fn_get_my_profile()
 RETURNS profiles
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select * from profiles where auth_user_id = auth.uid() limit 1;
$function$


CREATE OR REPLACE FUNCTION public.fn_get_public_endorsements(p_slug text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH creator_row AS (
    SELECT c.id FROM creators c WHERE c.slug = p_slug AND c.is_test = false
  ),
  confirmed AS (
    SELECT cam.would_hire_again, cam.endorsement_notes, cam.endorsement_submitted_at,
           cam.endorsement_public_consent, cam.sponsor_id
    FROM campaigns cam, creator_row cr
    WHERE cam.creator_id = cr.id
      AND cam.creator_confirmed AND cam.sponsor_confirmed
      AND cam.endorsement_submitted_at IS NOT NULL
  ),
  agg AS (
    SELECT count(*) AS total,
           count(*) FILTER (WHERE would_hire_again) AS yes_count
    FROM confirmed
  ),
  recent_notes AS (
    SELECT
      CASE WHEN c.endorsement_public_consent THEN p.display_name ELSE 'Verified sponsor' END AS sponsor_label,
      c.endorsement_notes AS note,
      to_char(c.endorsement_submitted_at, 'Mon YYYY') AS submitted_month
    FROM confirmed c
    LEFT JOIN profiles p ON p.id = c.sponsor_id
    WHERE c.endorsement_notes IS NOT NULL AND length(trim(c.endorsement_notes)) > 0
    ORDER BY c.endorsement_submitted_at DESC
    LIMIT 3
  )
  SELECT jsonb_build_object(
    'total_endorsements', COALESCE((SELECT total FROM agg), 0),
    'would_hire_again_pct', CASE WHEN (SELECT total FROM agg) > 0
       THEN round((SELECT yes_count FROM agg)::numeric / (SELECT total FROM agg) * 100)
       ELSE null END,
    'notes', COALESCE((SELECT jsonb_agg(row_to_json(recent_notes)) FROM recent_notes), '[]'::jsonb)
  );
$function$


CREATE OR REPLACE FUNCTION public.fn_get_public_profile(p_slug text)
 RETURNS TABLE(display_name text, niche text, location text, trust_score numeric, confidence numeric, badge_tier text, founding_cohort boolean, reliability_score numeric, verified_campaign_count bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT p.display_name, c.niche, c.location, c.trust_score, c.confidence::numeric,
         c.badge_tier, c.founding_cohort, c.reliability_score,
         (SELECT count(*) FROM campaigns cam WHERE cam.creator_id = c.id AND cam.creator_confirmed AND cam.sponsor_confirmed)
  FROM creators c
  JOIN profiles p ON p.id = c.id
  WHERE c.slug = p_slug AND c.is_test = false;
$function$


CREATE OR REPLACE FUNCTION public.fn_increment_evekit_view(p_slug text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  UPDATE creators SET profile_views = COALESCE(profile_views, 0) + 1 WHERE slug = p_slug AND is_test = false;
$function$


CREATE OR REPLACE FUNCTION public.fn_is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select fn_current_role() = 'admin';
$function$


CREATE OR REPLACE FUNCTION public.fn_is_team_member(p_team_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from team_members
    where team_id = p_team_id and sponsor_id = fn_current_profile_id()
  );
$function$


CREATE OR REPLACE FUNCTION public.fn_lookup_campaign_invite(p_token text)
 RETURNS TABLE(id uuid, sponsor_email text, sponsor_name text, description text, budget_range text, status text, expires_at timestamp with time zone, creator_display_name text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT cci.id, cci.sponsor_email, cci.sponsor_name, cci.description, cci.budget_range,
         cci.status, cci.expires_at, p.display_name AS creator_display_name
  FROM campaign_confirmation_invites cci
  JOIN profiles p ON p.id = cci.creator_id
  WHERE cci.token = p_token
  LIMIT 1;
$function$


CREATE OR REPLACE FUNCTION public.fn_lookup_team_invite(p_token text)
 RETURNS TABLE(id uuid, team_id uuid, email text, accepted_at timestamp with time zone, expires_at timestamp with time zone, team_name text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select ti.id, ti.team_id, ti.email, ti.accepted_at, ti.expires_at, t.name as team_name
  from team_invites ti
  join teams t on t.id = ti.team_id
  where ti.token = p_token
  limit 1;
$function$


CREATE OR REPLACE FUNCTION public.fn_notify_admin_on_signup()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_api_key text;
  v_admin_email text := 'gina.hamza@kitscore.co';
  v_subject text;
  v_body text;
  v_request_id bigint;
begin
  if new.role not in ('creator','sponsor') then
    return new;
  end if;

  begin
    select decrypted_secret into v_api_key
    from vault.decrypted_secrets
    where name = 'resend_api_key'
    limit 1;

    if v_api_key is null then
      raise exception 'resend_api_key not found in Vault';
    end if;

    v_subject := initcap(new.role::text) || ' signup: ' || coalesce(new.display_name, new.email);
    v_body := 'New ' || new.role || ' signed up on Kitscore.<br><br>' ||
              'Name: ' || coalesce(new.display_name, '(none)') || '<br>' ||
              'Email: ' || coalesce(new.email, '(none)') || '<br>' ||
              'Signed up: ' || new.created_at;

    v_request_id := net.http_post(
      url := 'https://api.resend.com/emails',
      headers := jsonb_build_object(
        'Authorization', 'Bearer ' || v_api_key,
        'Content-Type', 'application/json'
      ),
      body := jsonb_build_object(
        'from', 'Kitscore <hello@kitscore.co>',
        'to', jsonb_build_array(v_admin_email),
        'subject', v_subject,
        'html', v_body
      )
    );

    insert into public.notification_requests (net_request_id, kind, recipient_email)
    values (v_request_id, 'admin_signup_alert', v_admin_email);

  exception when others then
    insert into public.notification_failures (kind, recipient_email, error, attempts, created_at, last_attempted_at)
    values ('admin_signup_alert', v_admin_email, sqlerrm, 1, now(), now());
  end;

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_owned_team_count(p_owner_id uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT count(*)::int FROM teams
  WHERE owner_id = p_owner_id AND archived_at IS NULL;
$function$


CREATE OR REPLACE FUNCTION public.fn_recalc_badge_tier()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  verified_count int;
  new_tier text;
begin
  select count(*) into verified_count from campaigns
    where creator_id = coalesce(new.creator_id, old.creator_id) and status = 'verified';
  new_tier := case
    when verified_count >= 20 then 'platinum'
    when verified_count >= 10 then 'gold'
    when verified_count >= 5 then 'silver'
    when verified_count >= 2 then 'bronze'
    else 'none'
  end;
  update creators set badge_tier = new_tier, updated_at = now()
    where id = coalesce(new.creator_id, old.creator_id);
  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_recalc_brand_safety()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  target_creator uuid := coalesce(new.creator_id, old.creator_id);
  total numeric;
begin
  select 100 + coalesce(sum(p.penalty), 0) into total
    from brand_safety_answers a
    join brand_safety_penalties p on p.question_key = a.question_key and p.answer = a.answer
    where a.creator_id = target_creator;

  total := greatest(total, 0);

  insert into score_components (creator_id, component_key, label, weight, value, status)
  values (target_creator, 'brand_safety', 'Brand safety', 0.20, total, 'self_reported')
  on conflict (creator_id, component_key)
  do update set value = excluded.value, status = 'self_reported', updated_at = now();

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_recalc_creator_confidence(p_creator_id uuid)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_completeness numeric;
  v_verified_campaigns integer;
  v_sample_size numeric;
  v_evidence_total integer;
  v_evidence_verified integer;
  v_connections_total integer;
  v_connections_verified integer;
  v_verification_depth numeric;
  v_confidence numeric;
BEGIN
  v_completeness := creator_score_completeness(p_creator_id);

  SELECT COUNT(*) INTO v_verified_campaigns
  FROM campaigns WHERE creator_id = p_creator_id AND creator_confirmed = true AND sponsor_confirmed = true;
  v_sample_size := LEAST(v_verified_campaigns::numeric / 10, 1) * 100;

  SELECT COUNT(*), COUNT(*) FILTER (WHERE status = 'live_verified')
  INTO v_evidence_total, v_evidence_verified
  FROM evidence_uploads WHERE creator_id = p_creator_id;

  SELECT COUNT(*), COUNT(*) FILTER (WHERE verification_method = 'oauth')
  INTO v_connections_total, v_connections_verified
  FROM platform_connections WHERE creator_id = p_creator_id;

  v_verification_depth := CASE WHEN (v_evidence_total + v_connections_total) > 0
    THEN ((v_evidence_verified + v_connections_verified)::numeric / (v_evidence_total + v_connections_total)) * 100
    ELSE 0 END;

  v_confidence := ROUND(
    (v_completeness * 0.40) +
    (v_sample_size * 0.30) +
    (v_verification_depth * 0.30)
  );

  UPDATE creators SET confidence = v_confidence, updated_at = now() WHERE id = p_creator_id;
  RETURN v_confidence;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_recalc_engagement_quality_youtube()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_ratio numeric;
  v_value numeric;
begin
  if new.follower_count is null or new.follower_count = 0
     or new.video_count is null or new.video_count = 0
     or new.view_count is null then
    return new;
  end if;

  v_ratio := (new.view_count::numeric / new.video_count) / new.follower_count;

  v_value := case
    when v_ratio >= 1.0  then 90
    when v_ratio >= 0.5  then 80
    when v_ratio >= 0.2  then 70
    when v_ratio >= 0.05 then 55
    else 40
  end;

  insert into score_components (creator_id, component_key, label, weight, value, status)
  values (new.creator_id, 'engagement_quality_youtube', 'Engagement quality (YouTube)', 0.20, v_value, 'live_verified')
  on conflict (creator_id, component_key)
  do update set value = excluded.value, weight = excluded.weight, status = 'live_verified', updated_at = now();

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_recalc_evidence_component()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  target_creator uuid := new.creator_id;
  target_component text;
  approved_count integer;
  v_value numeric;
begin
  if new.status is distinct from 'live_verified' or old.status = 'live_verified' then
    return new;
  end if;

  target_component := case new.evidence_type
    when 'Audience' then 'audience_authenticity'
    when 'Analytics' then 'engagement_quality'
    when 'Campaign' then 'content_consistency'
    else null
  end;

  if target_component is null then
    return new;
  end if;

  select count(*) into approved_count
  from evidence_uploads
  where creator_id = target_creator
    and evidence_type = new.evidence_type
    and status = 'live_verified';

  v_value := least(85, 50 + 15 * approved_count);

  insert into score_components (creator_id, component_key, label, weight, value, status)
  values (
    target_creator,
    target_component,
    initcap(replace(target_component, '_', ' ')),
    0.20,
    v_value,
    'evidence_submitted'
  )
  on conflict (creator_id, component_key)
  do update set
    value = excluded.value,
    status = case when score_components.status = 'live_verified' then score_components.status else 'evidence_submitted' end,
    updated_at = now();

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_recalc_professionalism()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  target_creator uuid := new.creator_id;
  v_avg numeric;
begin
  select coalesce(avg(professionalism_rating), 0) * 20
  into v_avg
  from campaigns
  where creator_id = target_creator
    and endorsement_submitted_at is not null;

  insert into score_components (creator_id, component_key, label, weight, value, status)
  values (target_creator, 'professionalism', 'Professionalism', 0.20, v_avg, 'live_verified')
  on conflict (creator_id, component_key)
  do update set value = excluded.value, status = 'live_verified', updated_at = now();

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_recalc_trust_score()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  total numeric;
  v_creator_id uuid;
begin
  v_creator_id := coalesce(new.creator_id, old.creator_id);
  select coalesce(sum(value * weight), 0) into total
    from score_components where creator_id = v_creator_id;
  update creators set trust_score = round(total, 0), updated_at = now()
    where id = v_creator_id;
  perform fn_recalc_creator_confidence(v_creator_id);
  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_set_evekit_slug(p_slug text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_creator_id uuid := fn_current_profile_id();
  v_plan text;
  v_clean text := lower(trim(p_slug));
BEGIN
  IF v_creator_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Not signed in.');
  END IF;

  SELECT plan INTO v_plan FROM public.creators WHERE id = v_creator_id;
  IF v_plan IS DISTINCT FROM 'pro' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Custom vanity URLs are a Pro feature.');
  END IF;

  IF v_clean !~ '^[a-z0-9-]{3,40}$' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Use 3-40 lowercase letters, numbers, or hyphens only.');
  END IF;

  IF EXISTS (SELECT 1 FROM public.creators WHERE slug = v_clean AND id <> v_creator_id) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'That URL is already taken.');
  END IF;

  UPDATE public.creators SET slug = v_clean, updated_at = now() WHERE id = v_creator_id;
  RETURN jsonb_build_object('ok', true, 'slug', v_clean);
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_set_evidence_reviewed_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.status is distinct from old.status
     and new.status in ('live_verified', 'rejected') then
    new.reviewed_at := now();
  end if;
  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_set_founding_cohort()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if (select count(*) from creators) < 100 then
    new.founding_cohort := true;
  else
    new.founding_cohort := false;
  end if;
  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_team_audit_trail(p_team_id uuid)
 RETURNS TABLE(event_date timestamp with time zone, event_type text, actor_name text, subject_name text, detail text, status text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    e.created_at,
    'Evaluation'::text,
    sp.display_name,
    cr.display_name,
    CASE WHEN cl.name IS NOT NULL THEN 'Client: ' || cl.name ELSE '' END,
    (CASE WHEN e.unlocked THEN 'Unlocked' ELSE 'Locked' END) ||
      (CASE WHEN e.recommendation_verdict IS NOT NULL THEN ' / ' || e.recommendation_verdict ELSE '' END)
  FROM evaluations e
  LEFT JOIN profiles sp ON sp.id = e.sponsor_id
  LEFT JOIN profiles cr ON cr.id = e.creator_id
  LEFT JOIN clients cl ON cl.id = e.client_id
  WHERE e.team_id = p_team_id AND fn_is_team_member(p_team_id)

  UNION ALL

  SELECT
    COALESCE(ar.reviewed_at, ar.created_at),
    'Approval request'::text,
    req.display_name,
    COALESCE(target_cr.display_name, ar.action_type, '$29 unlock'),
    COALESCE(ar.note, '') || (CASE WHEN target_cl.name IS NOT NULL THEN (CASE WHEN ar.note IS NOT NULL THEN ' -- ' ELSE '' END) || 'Client: ' || target_cl.name ELSE '' END),
    ar.status || (CASE WHEN rev.display_name IS NOT NULL THEN ' by ' || rev.display_name ELSE '' END)
  FROM approval_requests ar
  LEFT JOIN profiles req ON req.id = ar.requested_by
  LEFT JOIN profiles rev ON rev.id = ar.reviewed_by
  LEFT JOIN evaluations target_e ON ar.target_type = 'evaluation' AND target_e.id = ar.target_id
  LEFT JOIN profiles target_cr ON target_cr.id = target_e.creator_id
  LEFT JOIN clients target_cl ON target_cl.id = target_e.client_id
  WHERE ar.team_id = p_team_id AND fn_is_team_member(p_team_id)

  ORDER BY 1;
$function$


CREATE OR REPLACE FUNCTION public.fn_team_clients(p_team_id uuid)
 RETURNS TABLE(client_id uuid, name text, status client_status, created_at timestamp with time zone, evaluation_count bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT c.id, c.name, c.status, c.created_at,
    (SELECT count(*) FROM evaluations e WHERE e.client_id = c.id)
  FROM clients c
  WHERE c.team_id = p_team_id
    AND fn_is_team_member(p_team_id)
  ORDER BY c.created_at DESC;
$function$


CREATE OR REPLACE FUNCTION public.fn_team_notes(p_team_id uuid)
 RETURNS TABLE(note_id uuid, author_id uuid, author_display_name text, creator_id uuid, creator_display_name text, content text, created_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT tn.id, tn.author_id, ap.display_name, tn.creator_id, cp.display_name, tn.content, tn.created_at
  FROM team_notes tn
  JOIN profiles ap ON ap.id = tn.author_id
  LEFT JOIN profiles cp ON cp.id = tn.creator_id
  WHERE tn.team_id = p_team_id
    AND fn_is_team_member(p_team_id)
  ORDER BY tn.created_at DESC;
$function$


CREATE OR REPLACE FUNCTION public.fn_team_pending_approvals(p_team_id uuid)
 RETURNS TABLE(request_id uuid, requested_by uuid, requester_display_name text, action_type text, target_type text, target_id uuid, note text, created_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT ar.id, ar.requested_by, p.display_name, ar.action_type, ar.target_type, ar.target_id, ar.note, ar.created_at
  FROM approval_requests ar
  JOIN profiles p ON p.id = ar.requested_by
  WHERE ar.team_id = p_team_id
    AND ar.status = 'pending'
    AND EXISTS (SELECT 1 FROM teams WHERE teams.id = p_team_id AND teams.owner_id = fn_current_profile_id())
  ORDER BY ar.created_at ASC;
$function$


CREATE OR REPLACE FUNCTION public.fn_team_roster(p_team_id uuid)
 RETURNS TABLE(member_id uuid, sponsor_id uuid, role text, display_name text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT tm.id, tm.sponsor_id, tm.role, p.display_name
  FROM team_members tm
  JOIN profiles p ON p.id = tm.sponsor_id
  WHERE tm.team_id = p_team_id
    AND fn_is_team_member(p_team_id);
$function$


CREATE OR REPLACE FUNCTION public.fn_team_score_alerts(p_team_id uuid)
 RETURNS TABLE(evaluation_id uuid, creator_id uuid, creator_name text, score_then numeric, score_now numeric, approved_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT e.id, c.id, p.display_name, e.trust_score_at_approval, c.trust_score, e.reviewed_at
  FROM evaluations e
  JOIN creators c ON c.id = e.creator_id
  JOIN profiles p ON p.id = c.id
  WHERE e.team_id = p_team_id
    AND fn_is_team_member(p_team_id)
    AND e.approval_status = 'approved'
    AND e.trust_score_at_approval IS NOT NULL
    AND c.trust_score < e.trust_score_at_approval
  ORDER BY (e.trust_score_at_approval - c.trust_score) DESC;
$function$


CREATE OR REPLACE FUNCTION public.fn_validate_campaign_confirmation()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if fn_is_admin() then
    return new;
  end if;

  if new.sponsor_confirmed is distinct from old.sponsor_confirmed
     and new.sponsor_id != fn_current_profile_id() then
    raise exception 'Only the sponsor on this campaign can set sponsor_confirmed';
  end if;
  if new.creator_confirmed is distinct from old.creator_confirmed
     and new.creator_id != fn_current_profile_id() then
    raise exception 'Only the creator on this campaign can set creator_confirmed';
  end if;

  if new.status is distinct from old.status then
    if new.status = 'verified' then
      if not (new.creator_confirmed and new.sponsor_confirmed) then
        raise exception 'Campaigns can only become verified once both parties confirm';
      end if;
    elsif new.status = 'disputed' then
      if old.status != 'pending' then
        raise exception 'Only a pending campaign can be disputed';
      end if;
      if new.creator_id != fn_current_profile_id() then
        raise exception 'Only the creator on this campaign can dispute it';
      end if;
      if old.creator_confirmed then
        raise exception 'A campaign you already confirmed cannot be disputed';
      end if;
      new.disputed_at := now();
    elsif new.status = 'pending' and old.status = 'disputed' then
      if new.creator_id != old.creator_id or new.sponsor_id != old.sponsor_id then
        raise exception 'A disputed campaign cannot be reassigned to a different creator or sponsor';
      end if;
      if fn_current_profile_id() != old.creator_id and fn_current_profile_id() != old.sponsor_id then
        raise exception 'Only the creator or sponsor on this campaign can resolve a dispute';
      end if;
      new.dispute_reason := null;
      new.disputed_at := null;
    else
      raise exception 'Invalid campaign status transition';
    end if;
  end if;

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_validate_creator_rating()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if fn_is_admin() then
    return new;
  end if;

  if (new.creator_rating is distinct from old.creator_rating)
     or (new.creator_outcome is distinct from old.creator_outcome) then

    if new.creator_id != fn_current_profile_id() then
      raise exception 'Only the creator on this campaign can rate the sponsor';
    end if;
    if old.status != 'verified' then
      raise exception 'Sponsor ratings can only be submitted on verified campaigns';
    end if;
  end if;

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_validate_endorsement()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if fn_is_admin() then
    return new;
  end if;

  if (new.sponsor_rating is distinct from old.sponsor_rating)
     or (new.communication_rating is distinct from old.communication_rating)
     or (new.professionalism_rating is distinct from old.professionalism_rating)
     or (new.deliverable_quality_rating is distinct from old.deliverable_quality_rating)
     or (new.would_hire_again is distinct from old.would_hire_again)
     or (new.endorsement_notes is distinct from old.endorsement_notes)
     or (new.endorsement_public_consent is distinct from old.endorsement_public_consent)
     or (new.endorsement_submitted_at is distinct from old.endorsement_submitted_at) then

    if new.sponsor_id != fn_current_profile_id() then
      raise exception 'Only the sponsor on this campaign can submit an endorsement';
    end if;
    if old.status != 'verified' then
      raise exception 'Endorsements can only be submitted on verified campaigns';
    end if;
    if old.endorsement_submitted_at is not null then
      raise exception 'Endorsement already submitted for this campaign';
    end if;
  end if;

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.fn_validate_evaluation_approval()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF fn_is_admin() THEN
    RETURN NEW;
  END IF;

  IF NEW.approval_status IS DISTINCT FROM OLD.approval_status THEN
    IF NEW.approval_status IN ('approved', 'rejected') THEN
      IF NOT EXISTS (
        SELECT 1 FROM teams WHERE teams.id = NEW.team_id AND teams.owner_id = fn_current_profile_id()
      ) THEN
        RAISE EXCEPTION 'Only the team owner can approve or reject an evaluation';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.fn_validate_evidence_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if fn_is_admin() then
    return new;
  end if;

  if new.status is distinct from old.status then
    raise exception 'Only an admin can change evidence review status';
  end if;

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_role text := new.raw_user_meta_data->>'role';
  v_display_name text := new.raw_user_meta_data->>'display_name';
  v_profile_id uuid;
begin
  if new.email_confirmed_at is null then
    return new;
  end if;

  if v_role is null or v_display_name is null then
    return new;
  end if;

  insert into public.profiles (auth_user_id, role, display_name, email)
  values (new.id, v_role::user_role, v_display_name, new.email)
  on conflict (auth_user_id) do nothing
  returning id into v_profile_id;

  if v_profile_id is null then
    select id into v_profile_id from public.profiles where auth_user_id = new.id;
  end if;

  if v_role = 'creator' then
    insert into public.creators (id) values (v_profile_id) on conflict (id) do nothing;
  elsif v_role = 'sponsor' then
    insert into public.sponsors (id, company_name) values (v_profile_id, v_display_name) on conflict (id) do nothing;
  end if;

  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.recalculate_sponsor_reliability(p_sponsor_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  total_confirmed INTEGER;
  score NUMERIC;
  reliability TEXT;
BEGIN
  SELECT COUNT(*) INTO total_confirmed
  FROM campaigns
  WHERE sponsor_id = p_sponsor_id
    AND creator_confirmed = TRUE
    AND sponsor_confirmed = TRUE;

  score := LEAST(total_confirmed * 10, 100);

  reliability := CASE
    WHEN total_confirmed = 0 THEN 'unrated'
    WHEN total_confirmed < 3 THEN 'new'
    WHEN score >= 80 THEN 'trusted'
    WHEN score >= 50 THEN 'established'
    ELSE 'building'
  END;

  UPDATE sponsors
  SET
    reliability_score = score,
    campaigns_completed = total_confirmed,
    payment_reliability = reliability,
    updated_at = now()
  WHERE id = p_sponsor_id;
END;
$function$


CREATE OR REPLACE FUNCTION public.trg_confidence_on_campaign_verified()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform fn_recalc_creator_confidence(coalesce(new.creator_id, old.creator_id));
  return new;
end;
$function$


CREATE OR REPLACE FUNCTION public.trg_sponsor_reliability_on_campaign()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.creator_confirmed = TRUE AND NEW.sponsor_confirmed = TRUE
     AND (OLD.creator_confirmed = FALSE OR OLD.sponsor_confirmed = FALSE) THEN
    PERFORM recalculate_sponsor_reliability(NEW.sponsor_id);
  END IF;
  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.trigger_reliability_on_endorsement()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.endorsement_submitted_at IS NOT NULL AND (
       OLD.endorsement_submitted_at IS NULL
       OR OLD.sponsor_rating IS DISTINCT FROM NEW.sponsor_rating
       OR OLD.communication_rating IS DISTINCT FROM NEW.communication_rating
       OR OLD.professionalism_rating IS DISTINCT FROM NEW.professionalism_rating
       OR OLD.deliverable_quality_rating IS DISTINCT FROM NEW.deliverable_quality_rating
       OR OLD.would_hire_again IS DISTINCT FROM NEW.would_hire_again
  ) THEN
    PERFORM compute_creator_reliability(NEW.creator_id);
  END IF;
  RETURN NEW;
END;
$function$


CREATE OR REPLACE FUNCTION public.trigger_reliability_on_verification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.creator_confirmed = true AND NEW.sponsor_confirmed = true
     AND (OLD.creator_confirmed = false OR OLD.sponsor_confirmed = false) THEN
    PERFORM compute_creator_reliability(NEW.creator_id);
  END IF;
  RETURN NEW;
END;
$function$


-- =============================================================
-- TRIGGERS  (grouped by table)
-- =============================================================

-- brand_safety_answers
CREATE TRIGGER trg_recalc_brand_safety AFTER INSERT OR UPDATE ON public.brand_safety_answers FOR EACH ROW EXECUTE FUNCTION fn_recalc_brand_safety();
-- campaigns
CREATE TRIGGER on_campaign_verified AFTER UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION trigger_reliability_on_verification();
-- campaigns
CREATE TRIGGER on_endorsement_submitted AFTER UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION trigger_reliability_on_endorsement();
-- campaigns
CREATE TRIGGER trg_campaign_mutual_confirm BEFORE UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_campaign_mutual_confirm();
-- campaigns
CREATE TRIGGER trg_recalc_badge_tier AFTER INSERT OR UPDATE OF status ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_recalc_badge_tier();
-- campaigns
CREATE TRIGGER trg_recalc_confidence_campaigns AFTER INSERT OR UPDATE OF status ON public.campaigns FOR EACH ROW EXECUTE FUNCTION trg_confidence_on_campaign_verified();
-- campaigns
CREATE TRIGGER trg_recalc_professionalism AFTER UPDATE ON public.campaigns FOR EACH ROW WHEN (((new.endorsement_submitted_at IS NOT NULL) AND (old.endorsement_submitted_at IS NULL))) EXECUTE FUNCTION fn_recalc_professionalism();
-- campaigns
CREATE TRIGGER trg_sponsor_reliability AFTER UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION trg_sponsor_reliability_on_campaign();
-- campaigns
CREATE TRIGGER trg_validate_campaign_confirmation BEFORE UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_validate_campaign_confirmation();
-- campaigns
CREATE TRIGGER trg_validate_creator_rating BEFORE UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_validate_creator_rating();
-- campaigns
CREATE TRIGGER trg_validate_endorsement BEFORE UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_validate_endorsement();
-- creators
CREATE TRIGGER trg_capture_trust_score_history AFTER UPDATE OF trust_score, confidence ON public.creators FOR EACH ROW EXECUTE FUNCTION fn_capture_trust_score_history();
-- creators
CREATE TRIGGER trg_generate_creator_slug BEFORE INSERT ON public.creators FOR EACH ROW EXECUTE FUNCTION fn_generate_creator_slug();
-- creators
CREATE TRIGGER trg_set_founding_cohort BEFORE INSERT ON public.creators FOR EACH ROW EXECUTE FUNCTION fn_set_founding_cohort();
-- evaluations
CREATE TRIGGER trg_capture_trust_score_at_approval BEFORE UPDATE ON public.evaluations FOR EACH ROW EXECUTE FUNCTION fn_capture_trust_score_at_approval();
-- evaluations
CREATE TRIGGER trg_evaluation_completeness_gate BEFORE INSERT ON public.evaluations FOR EACH ROW WHEN ((new.unlocked = true)) EXECUTE FUNCTION check_evaluation_completeness();
-- evaluations
CREATE TRIGGER trg_validate_evaluation_approval BEFORE UPDATE ON public.evaluations FOR EACH ROW EXECUTE FUNCTION fn_validate_evaluation_approval();
-- evidence_uploads
CREATE TRIGGER trg_confidence_on_evidence AFTER INSERT OR UPDATE OF status ON public.evidence_uploads FOR EACH ROW EXECUTE FUNCTION fn_confidence_on_evidence_change();
-- evidence_uploads
CREATE TRIGGER trg_recalc_evidence_component AFTER UPDATE ON public.evidence_uploads FOR EACH ROW WHEN (((new.status = 'live_verified'::evidence_status) AND (old.status IS DISTINCT FROM 'live_verified'::evidence_status))) EXECUTE FUNCTION fn_recalc_evidence_component();
-- evidence_uploads
CREATE TRIGGER trg_set_evidence_reviewed_at BEFORE UPDATE ON public.evidence_uploads FOR EACH ROW EXECUTE FUNCTION fn_set_evidence_reviewed_at();
-- evidence_uploads
CREATE TRIGGER trg_validate_evidence_status BEFORE UPDATE ON public.evidence_uploads FOR EACH ROW EXECUTE FUNCTION fn_validate_evidence_status();
-- platform_connections
CREATE TRIGGER trg_confidence_on_platform_connection AFTER INSERT OR UPDATE ON public.platform_connections FOR EACH ROW EXECUTE FUNCTION fn_confidence_on_platform_connection_change();
-- platform_connections
CREATE TRIGGER trg_enforce_platform_cap_connections BEFORE INSERT ON public.platform_connections FOR EACH ROW WHEN ((new.verification_method = 'oauth'::text)) EXECUTE FUNCTION fn_enforce_platform_cap();
-- platform_connections
CREATE TRIGGER trg_recalc_engagement_quality_youtube AFTER INSERT OR UPDATE OF follower_count, video_count, view_count ON public.platform_connections FOR EACH ROW WHEN (((new.platform = 'youtube'::text) AND (new.verification_method = 'oauth'::text))) EXECUTE FUNCTION fn_recalc_engagement_quality_youtube();
-- profiles
CREATE TRIGGER trg_notify_admin_on_signup AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION fn_notify_admin_on_signup();
-- score_components
CREATE TRIGGER trg_recalc_trust_score AFTER INSERT OR DELETE OR UPDATE OF value, weight, status ON public.score_components FOR EACH ROW EXECUTE FUNCTION fn_recalc_trust_score();
-- teams
CREATE TRIGGER trg_enforce_team_cap BEFORE INSERT ON public.teams FOR EACH ROW EXECUTE FUNCTION fn_enforce_team_cap();
-- watchlists
CREATE TRIGGER trg_enforce_watchlist_limit BEFORE INSERT ON public.watchlists FOR EACH ROW EXECUTE FUNCTION fn_enforce_watchlist_limit();

-- =============================================================
-- RLS POLICIES  (grouped by table)
-- =============================================================

CREATE POLICY admin_flags_admin_all ON public.admin_flags FOR ALL USING (fn_is_admin()) WITH CHECK (fn_is_admin());
CREATE POLICY approval_requests_member_insert ON public.approval_requests FOR INSERT WITH CHECK (((requested_by = fn_current_profile_id()) AND fn_is_team_member(team_id)));
CREATE POLICY approval_requests_owner_review ON public.approval_requests FOR UPDATE USING ((fn_is_admin() OR (team_id IN (SELECT teams.id FROM teams WHERE (teams.owner_id = fn_current_profile_id()))))) WITH CHECK ((fn_is_admin() OR (team_id IN (SELECT teams.id FROM teams WHERE (teams.owner_id = fn_current_profile_id())))));
CREATE POLICY approval_requests_team_select ON public.approval_requests FOR SELECT USING ((fn_is_team_member(team_id) OR fn_is_admin()));
CREATE POLICY audience_demographics_delete_own ON public.audience_demographics FOR DELETE USING (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY audience_demographics_insert_own ON public.audience_demographics FOR INSERT WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY audience_demographics_select_own ON public.audience_demographics FOR SELECT USING (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY audience_demographics_sponsor_read ON public.audience_demographics FOR SELECT USING ((fn_current_role() = 'sponsor'::user_role));
CREATE POLICY audience_demographics_update_own ON public.audience_demographics FOR UPDATE USING (((creator_id = fn_current_profile_id()) OR fn_is_admin())) WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY brand_safety_owner_only ON public.brand_safety_answers FOR ALL USING (((creator_id = fn_current_profile_id()) OR fn_is_admin())) WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY brand_safety_penalties_read_all ON public.brand_safety_penalties FOR SELECT USING (true);
CREATE POLICY brand_safety_scans_admin_only ON public.brand_safety_scans FOR ALL USING (fn_is_admin()) WITH CHECK (fn_is_admin());
CREATE POLICY "creators manage own invites" ON public.campaign_confirmation_invites FOR ALL USING ((creator_id IN (SELECT profiles.id FROM profiles WHERE (profiles.auth_user_id = auth.uid())))) WITH CHECK ((creator_id IN (SELECT profiles.id FROM profiles WHERE (profiles.auth_user_id = auth.uid()))));
CREATE POLICY campaigns_insert_involved ON public.campaigns FOR INSERT WITH CHECK (((creator_id = fn_current_profile_id()) OR (sponsor_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY campaigns_select_merged ON public.campaigns FOR SELECT USING (((creator_id = fn_current_profile_id()) OR (sponsor_id = fn_current_profile_id()) OR fn_is_admin() OR ((status = 'verified'::campaign_status) AND ((SELECT auth.role() AS role) = 'authenticated'::text))));
CREATE POLICY campaigns_update_involved ON public.campaigns FOR UPDATE USING (((creator_id = fn_current_profile_id()) OR (sponsor_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY clients_member_insert ON public.clients FOR INSERT WITH CHECK (((created_by = fn_current_profile_id()) AND fn_is_team_member(team_id)));
CREATE POLICY clients_member_select ON public.clients FOR SELECT USING ((fn_is_team_member(team_id) OR fn_is_admin()));
CREATE POLICY clients_member_update ON public.clients FOR UPDATE USING (fn_is_team_member(team_id)) WITH CHECK (fn_is_team_member(team_id));
CREATE POLICY clients_owner_delete ON public.clients FOR DELETE USING ((EXISTS (SELECT 1 FROM teams WHERE ((teams.id = clients.team_id) AND (teams.owner_id = fn_current_profile_id())))));
CREATE POLICY creator_collaborations_delete_own ON public.creator_collaborations FOR DELETE USING (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creator_collaborations_insert_own ON public.creator_collaborations FOR INSERT WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creator_collaborations_select_own ON public.creator_collaborations FOR SELECT USING (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creator_collaborations_update_own ON public.creator_collaborations FOR UPDATE USING (((creator_id = fn_current_profile_id()) OR fn_is_admin())) WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creator_press_mentions_delete_own ON public.creator_press_mentions FOR DELETE USING (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creator_press_mentions_insert_own ON public.creator_press_mentions FOR INSERT WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creator_press_mentions_select_own ON public.creator_press_mentions FOR SELECT USING (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creator_press_mentions_update_own ON public.creator_press_mentions FOR UPDATE USING (((creator_id = fn_current_profile_id()) OR fn_is_admin())) WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creators_insert_own ON public.creators FOR INSERT WITH CHECK (((id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY creators_select_authenticated ON public.creators FOR SELECT USING (((SELECT auth.role() AS role) = 'authenticated'::text));
CREATE POLICY creators_select_public_directory ON public.creators FOR SELECT USING (true);
CREATE POLICY creators_update_own ON public.creators FOR UPDATE USING (((id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY evaluations_admin_write ON public.evaluations FOR ALL USING (fn_is_admin()) WITH CHECK (fn_is_admin());
CREATE POLICY evaluations_insert_sponsor ON public.evaluations FOR INSERT WITH CHECK (((sponsor_id = fn_current_profile_id()) AND (EXISTS (SELECT 1 FROM sponsors WHERE (sponsors.id = fn_current_profile_id())))));
CREATE POLICY evaluations_select_own ON public.evaluations FOR SELECT USING ((fn_is_admin() OR ((sponsor_id = fn_current_profile_id()) AND ((unlocked = true) OR ((SELECT sponsors.plan FROM sponsors WHERE (sponsors.id = fn_current_profile_id())) = ANY (ARRAY['starter'::plan_tier, 'team'::plan_tier])))) OR ((team_id IS NOT NULL) AND fn_is_team_member(team_id))));
CREATE POLICY evaluations_team_approval ON public.evaluations FOR UPDATE USING (((team_id IS NOT NULL) AND fn_is_team_member(team_id))) WITH CHECK (((team_id IS NOT NULL) AND fn_is_team_member(team_id)));
CREATE POLICY evidence_owner_only ON public.evidence_uploads FOR ALL USING (((creator_id = fn_current_profile_id()) OR fn_is_admin())) WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY notification_failures_admin_select ON public.notification_failures FOR SELECT USING (fn_is_admin());
CREATE POLICY notification_requests_admin_select ON public.notification_requests FOR SELECT USING (fn_is_admin());
CREATE POLICY profiles_insert_own ON public.profiles FOR INSERT WITH CHECK ((auth_user_id = (SELECT auth.uid() AS uid)));
CREATE POLICY profiles_select_merged ON public.profiles FOR SELECT USING (((role = 'creator'::user_role) OR (auth_user_id = (SELECT auth.uid() AS uid)) OR fn_is_admin()));
CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE USING (((auth_user_id = (SELECT auth.uid() AS uid)) OR fn_is_admin()));
CREATE POLICY score_components_select_authenticated ON public.score_components FOR SELECT USING (((SELECT auth.role() AS role) = 'authenticated'::text));
CREATE POLICY score_components_write_own ON public.score_components FOR ALL USING (((creator_id = fn_current_profile_id()) OR fn_is_admin())) WITH CHECK (((creator_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY sponsors_owner_only ON public.sponsors FOR ALL USING (((id = fn_current_profile_id()) OR fn_is_admin())) WITH CHECK (((id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY sponsors_select_via_shared_campaign ON public.sponsors FOR SELECT USING ((EXISTS (SELECT 1 FROM campaigns WHERE ((campaigns.sponsor_id = sponsors.id) AND (campaigns.creator_id = fn_current_profile_id())))));
CREATE POLICY sponsors_select_via_shared_team ON public.sponsors FOR SELECT USING ((EXISTS (SELECT 1 FROM (team_members tm1 JOIN team_members tm2 ON ((tm1.team_id = tm2.team_id))) WHERE ((tm1.sponsor_id = fn_current_profile_id()) AND (tm2.sponsor_id = sponsors.id)))));
CREATE POLICY team_invites_accept_update ON public.team_invites FOR UPDATE USING (((accepted_at IS NULL) AND (expires_at > now()) AND (email = (SELECT p.email FROM profiles p WHERE (p.auth_user_id = (SELECT auth.uid() AS uid)))))) WITH CHECK ((email = (SELECT p.email FROM profiles p WHERE (p.auth_user_id = (SELECT auth.uid() AS uid)))));
CREATE POLICY team_invites_invitee_select ON public.team_invites FOR SELECT USING ((email = (SELECT p.email FROM profiles p WHERE (p.auth_user_id = (SELECT auth.uid() AS uid)))));
CREATE POLICY team_invites_member_select ON public.team_invites FOR SELECT USING ((fn_is_team_member(team_id) OR fn_is_admin()));
CREATE POLICY team_invites_owner_insert ON public.team_invites FOR INSERT WITH CHECK (((invited_by = fn_current_profile_id()) AND (team_id IN (SELECT teams.id FROM teams WHERE (teams.owner_id = fn_current_profile_id())))));
CREATE POLICY team_members_owner_delete ON public.team_members FOR DELETE USING ((fn_is_admin() OR (team_id IN (SELECT teams.id FROM teams WHERE (teams.owner_id = fn_current_profile_id())))));
CREATE POLICY team_members_owner_insert ON public.team_members FOR INSERT WITH CHECK (((fn_is_admin() OR (team_id IN (SELECT teams.id FROM teams WHERE (teams.owner_id = fn_current_profile_id())))) AND ((SELECT count(*) AS count FROM team_members team_members_1 WHERE (team_members_1.sponsor_id = team_members_1.sponsor_id)) < 2)));
CREATE POLICY team_members_owner_update ON public.team_members FOR UPDATE USING ((fn_is_admin() OR (team_id IN (SELECT teams.id FROM teams WHERE (teams.owner_id = fn_current_profile_id()))))) WITH CHECK ((fn_is_admin() OR (team_id IN (SELECT teams.id FROM teams WHERE (teams.owner_id = fn_current_profile_id())))));
CREATE POLICY team_members_select ON public.team_members FOR SELECT USING ((fn_is_team_member(team_id) OR fn_is_admin()));
CREATE POLICY team_members_self_join ON public.team_members FOR INSERT WITH CHECK (((sponsor_id = fn_current_profile_id()) AND (EXISTS (SELECT 1 FROM team_invites ti WHERE ((ti.team_id = team_members.team_id) AND (ti.email = (SELECT p.email FROM profiles p WHERE (p.id = fn_current_profile_id()))) AND (ti.expires_at > now())))) AND (role = 'member'::text) AND ((SELECT count(*) AS count FROM team_members team_members_1 WHERE (team_members_1.sponsor_id = fn_current_profile_id())) < 2)));
CREATE POLICY team_members_self_select ON public.team_members FOR SELECT USING ((sponsor_id = fn_current_profile_id()));
CREATE POLICY team_notes_author_delete ON public.team_notes FOR DELETE USING (((author_id = fn_current_profile_id()) OR fn_is_admin()));
CREATE POLICY team_notes_member_insert ON public.team_notes FOR INSERT WITH CHECK (((author_id = fn_current_profile_id()) AND fn_is_team_member(team_id)));
CREATE POLICY team_notes_member_select ON public.team_notes FOR SELECT USING ((fn_is_team_member(team_id) OR fn_is_admin()));
CREATE POLICY teams_delete ON public.teams FOR DELETE USING ((owner_id = fn_current_profile_id()));
CREATE POLICY teams_insert ON public.teams FOR INSERT WITH CHECK (((owner_id = fn_current_profile_id()) AND ((SELECT count(*) AS count FROM team_members WHERE (team_members.sponsor_id = fn_current_profile_id())) < 2)));
CREATE POLICY teams_select ON public.teams FOR SELECT USING (((owner_id = fn_current_profile_id()) OR fn_is_team_member(id)));
CREATE POLICY teams_update ON public.teams FOR UPDATE USING ((owner_id = fn_current_profile_id())) WITH CHECK ((owner_id = fn_current_profile_id()));
CREATE POLICY "creators read own score history" ON public.trust_score_history FOR SELECT USING ((creator_id IN (SELECT profiles.id FROM profiles WHERE (profiles.auth_user_id = auth.uid()))));
CREATE POLICY watchlists_owner_only ON public.watchlists FOR ALL USING (((sponsor_id = fn_current_profile_id()) OR fn_is_admin())) WITH CHECK (((sponsor_id = fn_current_profile_id()) OR fn_is_admin()));
