-- Kitscore database schema baseline -- snapshot as of 2026-07-04
--
-- Generated by querying pg_proc / pg_trigger / pg_policy directly against
-- the live Supabase project (tpcriphrfrrgywycviqv). This is a REFERENCE
-- SNAPSHOT documenting what exists, not a migration meant to be replayed.
-- See README.md in this folder for why this file exists and the practice
-- going forward.

-- =============================================================
-- FUNCTIONS
-- =============================================================

CREATE OR REPLACE FUNCTION public.check_evaluation_completeness()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  completeness NUMERIC;
BEGIN
  completeness := creator_score_completeness(NEW.creator_id);
  IF completeness < 50 THEN
    RAISE EXCEPTION
      'Creator score is only % complete. At least 50%% of score components must be filled before an evaluation can be unlocked.',
      completeness;
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.compute_creator_reliability(p_creator_id uuid)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_total_campaigns INTEGER;
  v_verified_campaigns INTEGER;
  v_completion_rate NUMERIC;
  v_avg_sponsor_rating NUMERIC;
  v_avg_communication NUMERIC;
  v_avg_professionalism NUMERIC;
  v_avg_deliverable NUMERIC;
  v_total_sponsors INTEGER;
  v_repeat_sponsors INTEGER;
  v_repeat_rate NUMERIC;
  v_would_hire_count INTEGER;
  v_would_hire_yes INTEGER;
  v_would_hire_pct NUMERIC;
  v_reliability NUMERIC;
BEGIN
  SELECT COUNT(*), COUNT(*) FILTER (WHERE creator_confirmed = true AND sponsor_confirmed = true)
  INTO v_total_campaigns, v_verified_campaigns
  FROM campaigns WHERE creator_id = p_creator_id;

  v_completion_rate := CASE WHEN v_total_campaigns > 0
    THEN (v_verified_campaigns::NUMERIC / v_total_campaigns) * 100
    ELSE 0 END;

  SELECT COALESCE(AVG(sponsor_rating), 0) * 20
  INTO v_avg_sponsor_rating
  FROM campaigns WHERE creator_id = p_creator_id AND sponsor_rating IS NOT NULL;

  SELECT COALESCE(AVG(communication_rating), 0) * 20,
         COALESCE(AVG(professionalism_rating), 0) * 20,
         COALESCE(AVG(deliverable_quality_rating), 0) * 20
  INTO v_avg_communication, v_avg_professionalism, v_avg_deliverable
  FROM campaigns WHERE creator_id = p_creator_id AND endorsement_submitted_at IS NOT NULL;

  SELECT COUNT(DISTINCT sponsor_id), COUNT(DISTINCT sponsor_id) FILTER (WHERE sponsor_count > 1)
  INTO v_total_sponsors, v_repeat_sponsors
  FROM (
    SELECT sponsor_id, COUNT(*) as sponsor_count
    FROM campaigns WHERE creator_id = p_creator_id AND creator_confirmed = true AND sponsor_confirmed = true
    GROUP BY sponsor_id
  ) sub;

  v_repeat_rate := CASE WHEN v_total_sponsors > 0
    THEN (v_repeat_sponsors::NUMERIC / v_total_sponsors) * 100
    ELSE 0 END;

  SELECT COUNT(*) FILTER (WHERE would_hire_again IS NOT NULL),
         COUNT(*) FILTER (WHERE would_hire_again = true)
  INTO v_would_hire_count, v_would_hire_yes
  FROM campaigns WHERE creator_id = p_creator_id;

  v_would_hire_pct := CASE WHEN v_would_hire_count > 0
    THEN (v_would_hire_yes::NUMERIC / v_would_hire_count) * 100
    ELSE 0 END;

  -- Weighted: completion 30%, sponsor rating 25%, endorsement avg 20%, repeat rate 15%, would-hire 10%
  v_reliability := (
    (v_completion_rate * 0.30) +
    (v_avg_sponsor_rating * 0.25) +
    (((v_avg_communication + v_avg_professionalism + v_avg_deliverable) / 3) * 0.20) +
    (v_repeat_rate * 0.15) +
    (v_would_hire_pct * 0.10)
  );

  UPDATE creators SET
    reliability_score = ROUND(v_reliability),
    repeat_sponsor_rate = ROUND(v_repeat_rate),
    would_hire_again_pct = ROUND(v_would_hire_pct),
    updated_at = NOW()
  WHERE id = p_creator_id;

  RETURN ROUND(v_reliability);
END;
$function$;

CREATE OR REPLACE FUNCTION public.creator_score_completeness(p_creator_id uuid)
 RETURNS numeric
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT CASE
    WHEN COUNT(*) = 0 THEN 0
    ELSE ROUND(
      COUNT(*) FILTER (WHERE value IS NOT NULL AND value > 0)::NUMERIC
      / COUNT(*)::NUMERIC * 100, 1
    )
  END
  FROM score_components
  WHERE creator_id = p_creator_id;
$function$;

CREATE OR REPLACE FUNCTION public.find_sponsor_by_profile_or_stripe(p_stripe_customer_id text, p_profile_id uuid DEFAULT NULL::uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id UUID;
BEGIN
  SELECT id INTO v_id FROM sponsors WHERE stripe_customer_id = p_stripe_customer_id LIMIT 1;
  IF v_id IS NOT NULL THEN RETURN v_id; END IF;
  IF p_profile_id IS NOT NULL THEN
    SELECT id INTO v_id FROM sponsors WHERE id = p_profile_id LIMIT 1;
  END IF;
  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_admin_list_profiles()
 RETURNS SETOF profiles
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not fn_is_admin() then
    raise exception 'Admin only';
  end if;
  return query select * from profiles order by created_at desc;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_campaign_mutual_confirm()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if new.creator_confirmed and new.sponsor_confirmed and old.status != 'verified' then
    new.status := 'verified';
    new.verified_at := now();
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_current_profile_id()
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select id from profiles where auth_user_id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.fn_current_role()
 RETURNS user_role
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select role from profiles where auth_user_id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.fn_enforce_watchlist_limit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  sponsor_plan plan_tier;
  current_count int;
  max_allowed int;
begin
  select plan into sponsor_plan from sponsors where id = new.sponsor_id;
  max_allowed := case when sponsor_plan = 'free' then 3 else null end;

  if max_allowed is not null then
    select count(*) into current_count from watchlists where sponsor_id = new.sponsor_id;
    if current_count >= max_allowed then
      raise exception 'Free plan is limited to % saved creators. Upgrade to save more.', max_allowed;
    end if;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_get_my_business_email()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select business_email from creators where id = fn_current_profile_id();
$function$;

CREATE OR REPLACE FUNCTION public.fn_get_my_profile()
 RETURNS profiles
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select * from profiles where auth_user_id = auth.uid() limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.fn_is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select fn_current_role() = 'admin';
$function$;

CREATE OR REPLACE FUNCTION public.fn_is_team_member(p_team_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from team_members
    where team_id = p_team_id and sponsor_id = fn_current_profile_id()
  );
$function$;

CREATE OR REPLACE FUNCTION public.fn_lookup_team_invite(p_token text)
 RETURNS TABLE(id uuid, team_id uuid, email text, accepted_at timestamp with time zone, expires_at timestamp with time zone, team_name text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select ti.id, ti.team_id, ti.email, ti.accepted_at, ti.expires_at, t.name as team_name
  from team_invites ti
  join teams t on t.id = ti.team_id
  where ti.token = p_token
  limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.fn_notify_admin_on_signup()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_api_key text;
  v_admin_email text := 'gina.hamza@kitscore.co';
  v_subject text;
  v_body text;
begin
  if new.role not in ('creator','sponsor') then
    return new;
  end if;

  begin
    select decrypted_secret into v_api_key
    from vault.decrypted_secrets
    where name = 'resend_api_key'
    limit 1;

    if v_api_key is null then
      raise exception 'resend_api_key not found in Vault';
    end if;

    v_subject := initcap(new.role::text) || ' signup: ' || coalesce(new.display_name, new.email);
    v_body := 'New ' || new.role || ' signed up on Kitscore.<br><br>' ||
              'Name: ' || coalesce(new.display_name, '(none)') || '<br>' ||
              'Email: ' || coalesce(new.email, '(none)') || '<br>' ||
              'Signed up: ' || new.created_at;

    perform net.http_post(
      url := 'https://api.resend.com/emails',
      headers := jsonb_build_object(
        'Authorization', 'Bearer ' || v_api_key,
        'Content-Type', 'application/json'
      ),
      body := jsonb_build_object(
        'from', 'Kitscore <hello@kitscore.co>',
        'to', jsonb_build_array(v_admin_email),
        'subject', v_subject,
        'html', v_body
      )
    );

  exception when others then
    insert into public.notification_failures (kind, recipient_email, error, attempts, created_at, last_attempted_at)
    values ('admin_signup_alert', v_admin_email, sqlerrm, 1, now(), now());
  end;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_recalc_badge_tier()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  verified_count int;
  new_tier text;
begin
  select count(*) into verified_count from campaigns
    where creator_id = coalesce(new.creator_id, old.creator_id) and status = 'verified';
  new_tier := case
    when verified_count >= 20 then 'platinum'
    when verified_count >= 10 then 'gold'
    when verified_count >= 5 then 'silver'
    when verified_count >= 2 then 'bronze'
    else 'none'
  end;
  update creators set badge_tier = new_tier, updated_at = now()
    where id = coalesce(new.creator_id, old.creator_id);
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_recalc_brand_safety()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  target_creator uuid := coalesce(new.creator_id, old.creator_id);
  total numeric;
begin
  select 100 + coalesce(sum(p.penalty), 0) into total
    from brand_safety_answers a
    join brand_safety_penalties p on p.question_key = a.question_key and p.answer = a.answer
    where a.creator_id = target_creator;

  total := greatest(total, 0);

  insert into score_components (creator_id, component_key, label, weight, value, status)
  values (target_creator, 'brand_safety', 'Brand safety', 0.20, total, 'live_verified')
  on conflict (creator_id, component_key)
  do update set value = excluded.value, status = 'live_verified', updated_at = now();

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_recalc_trust_score()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  total numeric;
begin
  select coalesce(sum(value * weight), 0) into total
    from score_components where creator_id = coalesce(new.creator_id, old.creator_id);
  update creators set trust_score = round(total, 0), updated_at = now()
    where id = coalesce(new.creator_id, old.creator_id);
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_set_founding_cohort()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if (select count(*) from creators) < 100 then
    new.founding_cohort := true;
  else
    new.founding_cohort := false;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_validate_campaign_confirmation()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if fn_is_admin() then
    return new;
  end if;

  if new.sponsor_confirmed is distinct from old.sponsor_confirmed
     and new.sponsor_id != fn_current_profile_id() then
    raise exception 'Only the sponsor on this campaign can set sponsor_confirmed';
  end if;
  if new.creator_confirmed is distinct from old.creator_confirmed
     and new.creator_id != fn_current_profile_id() then
    raise exception 'Only the creator on this campaign can set creator_confirmed';
  end if;

  -- Status guard. Runs after fn_campaign_mutual_confirm (alphabetically
  -- later trigger name), so new.status already reflects any automatic
  -- pending -> verified transition by the time we see it here.
  if new.status is distinct from old.status then
    if new.status = 'verified' then
      if not (new.creator_confirmed and new.sponsor_confirmed) then
        raise exception 'Campaigns can only become verified once both parties confirm';
      end if;
    elsif new.status = 'disputed' then
      if old.status != 'pending' then
        raise exception 'Only a pending campaign can be disputed';
      end if;
      if new.creator_id != fn_current_profile_id() then
        raise exception 'Only the creator on this campaign can dispute it';
      end if;
      if old.creator_confirmed then
        raise exception 'A campaign you already confirmed cannot be disputed';
      end if;
      new.disputed_at := now();
    elsif new.status = 'pending' and old.status = 'disputed' then
      if new.creator_id != old.creator_id or new.sponsor_id != old.sponsor_id then
        raise exception 'A disputed campaign cannot be reassigned to a different creator or sponsor';
      end if;
      if fn_current_profile_id() != old.creator_id and fn_current_profile_id() != old.sponsor_id then
        raise exception 'Only the creator or sponsor on this campaign can resolve a dispute';
      end if;
      new.dispute_reason := null;
      new.disputed_at := null;
    else
      raise exception 'Invalid campaign status transition';
    end if;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_validate_creator_rating()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if fn_is_admin() then
    return new;
  end if;

  if (new.creator_rating is distinct from old.creator_rating)
     or (new.creator_outcome is distinct from old.creator_outcome) then

    if new.creator_id != fn_current_profile_id() then
      raise exception 'Only the creator on this campaign can rate the sponsor';
    end if;
    if old.status != 'verified' then
      raise exception 'Sponsor ratings can only be submitted on verified campaigns';
    end if;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_validate_endorsement()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if fn_is_admin() then
    return new;
  end if;

  if (new.sponsor_rating is distinct from old.sponsor_rating)
     or (new.communication_rating is distinct from old.communication_rating)
     or (new.professionalism_rating is distinct from old.professionalism_rating)
     or (new.deliverable_quality_rating is distinct from old.deliverable_quality_rating)
     or (new.would_hire_again is distinct from old.would_hire_again)
     or (new.endorsement_notes is distinct from old.endorsement_notes)
     or (new.endorsement_submitted_at is distinct from old.endorsement_submitted_at) then

    if new.sponsor_id != fn_current_profile_id() then
      raise exception 'Only the sponsor on this campaign can submit an endorsement';
    end if;
    if old.status != 'verified' then
      raise exception 'Endorsements can only be submitted on verified campaigns';
    end if;
    if old.endorsement_submitted_at is not null then
      raise exception 'Endorsement already submitted for this campaign';
    end if;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_validate_evidence_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if fn_is_admin() then
    return new;
  end if;

  if new.status is distinct from old.status then
    raise exception 'Only an admin can change evidence review status';
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_role text := new.raw_user_meta_data->>'role';
  v_display_name text := new.raw_user_meta_data->>'display_name';
  v_profile_id uuid;
begin
  -- Only act once the user's email is actually confirmed (or confirmation isn't required)
  if new.email_confirmed_at is null then
    return new;
  end if;

  -- Nothing to do if signup metadata is missing (shouldn't happen, but stay safe)
  if v_role is null or v_display_name is null then
    return new;
  end if;

  insert into public.profiles (auth_user_id, role, display_name, email)
  values (new.id, v_role::user_role, v_display_name, new.email)
  on conflict (auth_user_id) do nothing
  returning id into v_profile_id;

  -- If the row already existed (e.g. race with client-side ensureProfile), fetch its id
  if v_profile_id is null then
    select id into v_profile_id from public.profiles where auth_user_id = new.id;
  end if;

  if v_role = 'creator' then
    insert into public.creators (id) values (v_profile_id) on conflict (id) do nothing;
  elsif v_role = 'sponsor' then
    insert into public.sponsors (id, company_name) values (v_profile_id, v_display_name) on conflict (id) do nothing;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.recalculate_creator_reliability(p_creator_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_total_verified      INTEGER;
  v_total_sponsors      INTEGER;
  v_repeat_sponsors     INTEGER;
  v_would_hire_count    INTEGER;
  v_would_hire_pct      NUMERIC;
  v_avg_comm            NUMERIC;
  v_avg_prof            NUMERIC;
  v_avg_quality         NUMERIC;
  v_repeat_rate         NUMERIC;
  v_reliability         NUMERIC;
BEGIN
  SELECT COUNT(*) INTO v_total_verified
  FROM campaigns WHERE creator_id = p_creator_id AND creator_confirmed = TRUE AND sponsor_confirmed = TRUE;

  IF v_total_verified = 0 THEN
    UPDATE creators SET reliability_score = 0, repeat_sponsor_rate = 0, would_hire_again_pct = 0, updated_at = now()
    WHERE id = p_creator_id;
    RETURN;
  END IF;

  SELECT COUNT(DISTINCT sponsor_id) INTO v_total_sponsors
  FROM campaigns WHERE creator_id = p_creator_id AND creator_confirmed = TRUE AND sponsor_confirmed = TRUE;

  SELECT COUNT(*) INTO v_repeat_sponsors FROM (
    SELECT sponsor_id FROM campaigns
    WHERE creator_id = p_creator_id AND creator_confirmed = TRUE AND sponsor_confirmed = TRUE
    GROUP BY sponsor_id HAVING COUNT(*) > 1
  ) sub;

  v_repeat_rate := CASE WHEN v_total_sponsors > 0
    THEN ROUND((v_repeat_sponsors::NUMERIC / v_total_sponsors) * 100, 1) ELSE 0 END;

  SELECT COUNT(*) INTO v_would_hire_count
  FROM campaigns WHERE creator_id = p_creator_id AND creator_confirmed = TRUE AND sponsor_confirmed = TRUE AND would_hire_again = TRUE;

  v_would_hire_pct := CASE WHEN v_total_verified > 0
    THEN ROUND((v_would_hire_count::NUMERIC / v_total_verified) * 100, 1) ELSE 0 END;

  SELECT COALESCE(AVG(communication_rating), 0), COALESCE(AVG(professionalism_rating), 0), COALESCE(AVG(deliverable_quality_rating), 0)
  INTO v_avg_comm, v_avg_prof, v_avg_quality
  FROM campaigns
  WHERE creator_id = p_creator_id AND creator_confirmed = TRUE AND sponsor_confirmed = TRUE AND communication_rating IS NOT NULL;

  -- Weighted: campaign count (cap 20) 30% + would-hire 30% + avg ratings 25% + repeat rate 15%
  v_reliability := ROUND(
    LEAST(v_total_verified, 20) / 20.0 * 30
    + (v_would_hire_pct / 100.0) * 30
    + ((v_avg_comm + v_avg_prof + v_avg_quality) / 15.0) * 25
    + (v_repeat_rate / 100.0) * 15
  , 1);

  UPDATE creators SET
    reliability_score = LEAST(v_reliability, 100),
    repeat_sponsor_rate = v_repeat_rate,
    would_hire_again_pct = v_would_hire_pct,
    updated_at = now()
  WHERE id = p_creator_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.recalculate_sponsor_reliability(p_sponsor_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  total_confirmed INTEGER;
  score NUMERIC;
  reliability TEXT;
BEGIN
  SELECT COUNT(*) INTO total_confirmed
  FROM campaigns WHERE sponsor_id = p_sponsor_id AND creator_confirmed = TRUE AND sponsor_confirmed = TRUE;

  score := LEAST(total_confirmed * 10, 100);

  reliability := CASE
    WHEN total_confirmed = 0 THEN 'unrated'
    WHEN total_confirmed < 3 THEN 'new'
    WHEN score >= 80 THEN 'trusted'
    WHEN score >= 50 THEN 'established'
    ELSE 'building'
  END;

  UPDATE sponsors SET
    reliability_score = score,
    campaigns_completed = total_confirmed,
    payment_reliability = reliability,
    updated_at = now()
  WHERE id = p_sponsor_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_creator_reliability_on_campaign()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF (NEW.creator_confirmed = TRUE AND NEW.sponsor_confirmed = TRUE)
     AND (OLD.creator_confirmed = FALSE OR OLD.sponsor_confirmed = FALSE
          OR OLD.would_hire_again IS DISTINCT FROM NEW.would_hire_again
          OR OLD.communication_rating IS DISTINCT FROM NEW.communication_rating) THEN
    PERFORM recalculate_creator_reliability(NEW.creator_id);
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_sponsor_reliability_on_campaign()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.creator_confirmed = TRUE AND NEW.sponsor_confirmed = TRUE
     AND (OLD.creator_confirmed = FALSE OR OLD.sponsor_confirmed = FALSE) THEN
    PERFORM recalculate_sponsor_reliability(NEW.sponsor_id);
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.trigger_reliability_on_endorsement()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.endorsement_submitted_at IS NOT NULL AND OLD.endorsement_submitted_at IS NULL THEN
    PERFORM compute_creator_reliability(NEW.creator_id);
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.trigger_reliability_on_verification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.creator_confirmed = true AND NEW.sponsor_confirmed = true
     AND (OLD.creator_confirmed = false OR OLD.sponsor_confirmed = false) THEN
    PERFORM compute_creator_reliability(NEW.creator_id);
  END IF;
  RETURN NEW;
END;
$function$;

-- =============================================================
-- TRIGGERS  (grouped by table)
-- =============================================================

-- auth.users
CREATE TRIGGER trg_handle_new_auth_user_insert AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_auth_user();
CREATE TRIGGER trg_handle_new_auth_user_confirm AFTER UPDATE ON auth.users FOR EACH ROW WHEN ((old.email_confirmed_at IS NULL) AND (new.email_confirmed_at IS NOT NULL)) EXECUTE FUNCTION handle_new_auth_user();

-- profiles
CREATE TRIGGER trg_notify_admin_on_signup AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION fn_notify_admin_on_signup();

-- creators
CREATE TRIGGER trg_set_founding_cohort BEFORE INSERT ON public.creators FOR EACH ROW EXECUTE FUNCTION fn_set_founding_cohort();

-- campaigns
CREATE TRIGGER trg_campaign_mutual_confirm BEFORE UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_campaign_mutual_confirm();
CREATE TRIGGER trg_validate_campaign_confirmation BEFORE UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_validate_campaign_confirmation();
CREATE TRIGGER trg_validate_endorsement BEFORE UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_validate_endorsement();
CREATE TRIGGER trg_validate_creator_rating BEFORE UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_validate_creator_rating();
CREATE TRIGGER trg_recalc_badge_tier AFTER INSERT OR UPDATE OF status ON public.campaigns FOR EACH ROW EXECUTE FUNCTION fn_recalc_badge_tier();
CREATE TRIGGER trg_creator_reliability AFTER UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION trg_creator_reliability_on_campaign();
CREATE TRIGGER trg_sponsor_reliability AFTER UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION trg_sponsor_reliability_on_campaign();
CREATE TRIGGER on_campaign_verified AFTER UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION trigger_reliability_on_verification();
CREATE TRIGGER on_endorsement_submitted AFTER UPDATE ON public.campaigns FOR EACH ROW EXECUTE FUNCTION trigger_reliability_on_endorsement();

-- evidence_uploads
CREATE TRIGGER trg_validate_evidence_status BEFORE UPDATE ON public.evidence_uploads FOR EACH ROW EXECUTE FUNCTION fn_validate_evidence_status();

-- evaluations
CREATE TRIGGER trg_evaluation_completeness_gate BEFORE INSERT ON public.evaluations FOR EACH ROW WHEN (new.unlocked = true) EXECUTE FUNCTION check_evaluation_completeness();

-- score_components
CREATE TRIGGER trg_recalc_trust_score AFTER INSERT OR DELETE OR UPDATE OF value, weight ON public.score_components FOR EACH ROW EXECUTE FUNCTION fn_recalc_trust_score();

-- brand_safety_answers
CREATE TRIGGER trg_recalc_brand_safety AFTER INSERT OR UPDATE ON public.brand_safety_answers FOR EACH ROW EXECUTE FUNCTION fn_recalc_brand_safety();

-- watchlists
CREATE TRIGGER trg_enforce_watchlist_limit BEFORE INSERT ON public.watchlists FOR EACH ROW EXECUTE FUNCTION fn_enforce_watchlist_limit();

-- =============================================================
-- RLS POLICIES  (grouped by table)
-- =============================================================

-- brand_safety_answers
CREATE POLICY brand_safety_owner_only ON public.brand_safety_answers FOR ALL
  USING (creator_id = fn_current_profile_id() OR fn_is_admin())
  WITH CHECK (creator_id = fn_current_profile_id() OR fn_is_admin());

-- brand_safety_penalties (reference/lookup table, intentionally public)
CREATE POLICY brand_safety_penalties_read_all ON public.brand_safety_penalties FOR SELECT USING (true);

-- campaigns
CREATE POLICY campaigns_insert_involved ON public.campaigns FOR INSERT
  WITH CHECK (creator_id = fn_current_profile_id() OR sponsor_id = fn_current_profile_id() OR fn_is_admin());
CREATE POLICY campaigns_select_involved ON public.campaigns FOR SELECT
  USING (creator_id = fn_current_profile_id() OR sponsor_id = fn_current_profile_id() OR fn_is_admin());
CREATE POLICY campaigns_select_verified_public ON public.campaigns FOR SELECT
  USING (status = 'verified' AND auth.role() = 'authenticated');
CREATE POLICY campaigns_update_involved ON public.campaigns FOR UPDATE
  USING (creator_id = fn_current_profile_id() OR sponsor_id = fn_current_profile_id() OR fn_is_admin());

-- creators
CREATE POLICY creators_insert_own ON public.creators FOR INSERT
  WITH CHECK (id = fn_current_profile_id() OR fn_is_admin());
CREATE POLICY creators_select_authenticated ON public.creators FOR SELECT
  USING (auth.role() = 'authenticated');
CREATE POLICY creators_select_public_directory ON public.creators FOR SELECT
  USING (true);
CREATE POLICY creators_update_own ON public.creators FOR UPDATE
  USING (id = fn_current_profile_id() OR fn_is_admin());

-- evaluations
CREATE POLICY evaluations_admin_write ON public.evaluations FOR ALL
  USING (fn_is_admin()) WITH CHECK (fn_is_admin());
CREATE POLICY evaluations_insert_sponsor ON public.evaluations FOR INSERT
  WITH CHECK (sponsor_id = fn_current_profile_id() AND EXISTS (SELECT 1 FROM sponsors WHERE sponsors.id = fn_current_profile_id()));
CREATE POLICY evaluations_select_own ON public.evaluations FOR SELECT
  USING (
    fn_is_admin()
    OR (sponsor_id = fn_current_profile_id() AND (unlocked = true OR (SELECT sponsors.plan FROM sponsors WHERE sponsors.id = fn_current_profile_id()) = ANY (ARRAY['starter'::plan_tier, 'team'::plan_tier])))
    OR (team_id IS NOT NULL AND fn_is_team_member(team_id))
  );
CREATE POLICY evaluations_team_approval ON public.evaluations FOR UPDATE
  USING (team_id IS NOT NULL AND fn_is_team_member(team_id))
  WITH CHECK (team_id IS NOT NULL AND fn_is_team_member(team_id));

-- evidence_uploads
CREATE POLICY evidence_owner_only ON public.evidence_uploads FOR ALL
  USING (creator_id = fn_current_profile_id() OR fn_is_admin())
  WITH CHECK (creator_id = fn_current_profile_id() OR fn_is_admin());

-- profiles
CREATE POLICY profiles_insert_own ON public.profiles FOR INSERT
  WITH CHECK (auth_user_id = auth.uid());
CREATE POLICY profiles_select_creators_public ON public.profiles FOR SELECT
  USING (role = 'creator');
CREATE POLICY profiles_select_own ON public.profiles FOR SELECT
  USING (auth_user_id = auth.uid() OR fn_is_admin());
CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE
  USING (auth_user_id = auth.uid() OR fn_is_admin());

-- score_components
CREATE POLICY score_components_select_authenticated ON public.score_components FOR SELECT
  USING (auth.role() = 'authenticated');
CREATE POLICY score_components_write_own ON public.score_components FOR ALL
  USING (creator_id = fn_current_profile_id() OR fn_is_admin())
  WITH CHECK (creator_id = fn_current_profile_id() OR fn_is_admin());

-- sponsors
CREATE POLICY sponsors_owner_only ON public.sponsors FOR ALL
  USING (id = fn_current_profile_id() OR fn_is_admin())
  WITH CHECK (id = fn_current_profile_id() OR fn_is_admin());
CREATE POLICY sponsors_select_via_shared_campaign ON public.sponsors FOR SELECT
  USING (EXISTS (SELECT 1 FROM campaigns WHERE campaigns.sponsor_id = sponsors.id AND campaigns.creator_id = fn_current_profile_id()));

-- team_invites
CREATE POLICY team_invites_accept_update ON public.team_invites FOR UPDATE
  USING (accepted_at IS NULL AND expires_at > now() AND email = (SELECT p.email FROM profiles p WHERE p.auth_user_id = auth.uid()));
CREATE POLICY team_invites_member_select ON public.team_invites FOR SELECT
  USING (fn_is_team_member(team_id) OR fn_is_admin());
CREATE POLICY team_invites_owner_insert ON public.team_invites FOR INSERT
  WITH CHECK (invited_by = fn_current_profile_id() AND team_id IN (SELECT teams.id FROM teams WHERE teams.owner_id = fn_current_profile_id()));

-- team_members
CREATE POLICY team_members_owner_manage ON public.team_members FOR ALL
  USING (fn_is_admin() OR team_id IN (SELECT teams.id FROM teams WHERE teams.owner_id = fn_current_profile_id()))
  WITH CHECK (fn_is_admin() OR team_id IN (SELECT teams.id FROM teams WHERE teams.owner_id = fn_current_profile_id()));
CREATE POLICY team_members_select ON public.team_members FOR SELECT
  USING (fn_is_team_member(team_id) OR fn_is_admin());

-- team_notes
CREATE POLICY team_notes_author_delete ON public.team_notes FOR DELETE
  USING (author_id = fn_current_profile_id() OR fn_is_admin());
CREATE POLICY team_notes_member_insert ON public.team_notes FOR INSERT
  WITH CHECK (author_id = fn_current_profile_id() AND fn_is_team_member(team_id));
CREATE POLICY team_notes_member_select ON public.team_notes FOR SELECT
  USING (fn_is_team_member(team_id) OR fn_is_admin());

-- teams
CREATE POLICY teams_delete ON public.teams FOR DELETE
  USING (owner_id IN (SELECT profiles.id FROM profiles WHERE profiles.auth_user_id = auth.uid()));
CREATE POLICY teams_insert ON public.teams FOR INSERT
  WITH CHECK (owner_id IN (SELECT profiles.id FROM profiles WHERE profiles.auth_user_id = auth.uid()));
CREATE POLICY teams_select ON public.teams FOR SELECT
  USING (owner_id IN (SELECT profiles.id FROM profiles WHERE profiles.auth_user_id = auth.uid()) OR fn_is_team_member(id));
CREATE POLICY teams_update ON public.teams FOR UPDATE
  USING (owner_id IN (SELECT profiles.id FROM profiles WHERE profiles.auth_user_id = auth.uid()))
  WITH CHECK (owner_id IN (SELECT profiles.id FROM profiles WHERE profiles.auth_user_id = auth.uid()));

-- watchlists
CREATE POLICY watchlists_owner_only ON public.watchlists FOR ALL
  USING (sponsor_id = fn_current_profile_id() OR fn_is_admin())
  WITH CHECK (sponsor_id = fn_current_profile_id() OR fn_is_admin());
